openapi: 3.0.0
info:
  title: 'Chat GPT API'
  description: 'Chat GPT API description'
  contact:
    email: mahbubul7497@gmail.com
  version: 1.0.0
paths:
  /api/v1/login:
    post:
      tags:
        - Authentication
      summary: 'Sign in with email & password'
      description: 'SignIn by email, password'
      operationId: login
      requestBody:
        description: 'Customer credentials'
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$'
                  example: pdamore@example.net
                password:
                  type: string
                  format: password
                  example: '123456'
              type: object
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: 'SignIn successfully!'
                type: object
        422:
          description: 'Wrong credentials response'
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: 'Sorry, wrong email address or password. Please try again'
                type: object
  /api/v1/chat:
    post:
      tags:
        - 'Chat By Open AI'
      summary: 'Chat By Open AI'
      description: 'Chat By Open AI'
      operationId: chatByOpenAI
      requestBody:
        description: Credentials
        required: true
        content:
          application/json:
            schema:
              required:
                - chat
              properties:
                chat:
                  type: string
                  example: Hello
              type: object
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: 'Hello! How can I assist you today?'
                type: object
      security:
        -
          sanctum: []
  /api/v1/chat-histories:
    get:
      tags:
        - 'Chat By Open AI'
      summary: 'Chat Histories'
      description: 'Chat Histories'
      operationId: chatHistories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: 'Chat histories'
                type: object
      security:
        -
          sanctum: []
components:
  securitySchemes:
    sanctum:
      type: apiKey
      description: 'Enter token in format (Bearer <token>)'
      name: Authorization
      in: header
